### ISSUE TITLE
License

### ISSUE THREAD

**Issue by tbroyer** [didierfred/GreenIT-Analysis#13]
Bonjour,

Une (grosse) partie du code d'analyse des bonnes pratiques semble avoir été copiée/collée depuis EcoMeter, et enfreint la license Affero GPL: aucune mention des auteurs / copyright, et changement de license en MPL.

Ne mettant plus d'énergie à maintenir EcoMeter, je soutiens cette initiative de reproduire ces analyses dans un plugin de navigateur, mais la license d'EcoMeter avait été soigneusement choisie et doit être respectée (d'autant plus par un membre de la communauté), même si je ne doute pas une seule seconde qu'il s'agisse de méconnaissance et/ou “manque d'attention”, et pas de malveillance.

/cc @Bornholm, @Cadoles, @atolcd, @lowki, @logomotion

**Comment by didierfred** [comment]
C'est une erreur de ma part , j'en suis désolé , j'ai effectivement repris du code et j'ai oublié le coté copyright / license . Je vais régulariser le point 
Je connais peu le sujet , cela veut t-il dire que je dois passer tout le code sur la license  Affero GPL car elle n'est pas compatible avec MPL ?

**Comment by tbroyer** [comment]
> C'est une erreur de ma part , j'en suis désolé , j'ai effectivement repris du code et j'ai oublié le coté copyright / license . Je vais régulariser le point

Je pense que ça nous est tous arrivé à un moment ou un autre. Ça ne devient vraiment problématique que lorsqu'on redistribue le code (comme ici une extension installable par quiconque).

> Je connais peu le sujet , cela veut t-il dire que je dois passer tout le code sur la license Affero GPL car elle n'est pas compatible avec MPL ?

Oui, la GPL/AGPL étant "virale".
Il y a probablement moyen de garder une partie du code sous MPL: par exemple en exécutant tout le code GPL dans `analyseFrame.js`, qui (si j'ai bien compris) est injecté dans la page et communique avec l'extension à proprement parler; dans ce cas, `analyseFrame.js` pourrait être sous AGPL et le reste de l'extension sous MPL (et ils communiquent par un "protocole" bien défini, et indépendant du code d'origine d'EcoMeter).
Est-ce que le jeu en vaut la chandelle par contre ?

**Comment by didierfred** [comment]
J'ai tout passé en license AGPL , c'est plus simple et j'ai fait référence à EcoMeter dans le README et les sources concernées (utils.js & analyseFrame.js)
